// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace QuizAppML.Model
{
    public class ModelInput
    {
        [ColumnName("date"), LoadColumn(0)]
        public string Date { get; set; }


        [ColumnName("precipitation"), LoadColumn(1)]
        public float Precipitation { get; set; }


        [ColumnName("temp_max"), LoadColumn(2)]
        public float Temp_max { get; set; }


        [ColumnName("temp_min"), LoadColumn(3)]
        public float Temp_min { get; set; }


        [ColumnName("wind"), LoadColumn(4)]
        public float Wind { get; set; }


        [ColumnName("weather"), LoadColumn(5)]
        public string Weather { get; set; }


    }
}
