//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_article
    {
        public int art_id { get; set; }
        public string art_content { get; set; }
        public string art_heading { get; set; }
        public string art_auth { get; set; }
        public string art_img { get; set; }
    }
}
